import Head from 'next/head'
import { MasterPage } from '../components/MasterPage'
import { Box, Button, Grid } from '@mui/material'
import useMessageBox from '../services/message-box.service'
import { MessageBoxComp } from '../components/feedback/MessageBox'

import { FormContainer, PasswordElement, TextFieldElement } from 'react-hook-form-mui'


export default function Home() {
  const { messageBox } = useMessageBox();

  const onSubmit = (data: any) => {
    console.log(data);

  }
  //messageBox.confirm(`Deseja realmente remover?`, async () => { console.log("Ok!") }

  return <MasterPage hideNavigation={true}>
    <Head>
      <title>Problem Company App - Welcome login</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.svg" />
    </Head>
    <Box
      display="flex"
      justifyContent="center"
      alignItems="center"
      minHeight="100vh"
    >
      <Grid item xs={3}>
        <h2>Login</h2>
        <FormContainer onSuccess={onSubmit}
          FormProps={{
            'aria-autocomplete': 'none',
            autoComplete: 'new-password'
          }}>

          <TextFieldElement
            required
            type={'email'}
            margin={'dense'}
            label={'Email'}
            name={'email'}
          /><br />


          <PasswordElement margin={'dense'}
            label={'Password'}
            required
            name={'password'}
          /><br />

          <Button type={'submit'} color={'primary'} variant={'contained'}>Submit</Button>
        </FormContainer>
        <MessageBoxComp messageBox={messageBox} />
      </Grid>
    </Box>

  </MasterPage >
}
